### ISSUE TITLE
haroopad can't run on windows platform

### ISSUE THREAD

**Issue by lwl5219** [rhiokim/haroopad#363]
**bug**
When i first installed haroopad and run, it had running very well. When i click the haroopad program, there is nothing occured. Although the haroopad process always running in background.

My haroopad version is v0.12.0-i386. I uninstall it, then install it again or repair it. The problem is  still not disappear.

**Comment by rhiokim** [comment]
We'll have the time for about this on window platform. Please look forward to the next version.

link: http://haroopad.userecho.com/topic/457957-windows-7-sp1-64bit-cannot-install/

**Comment by rhiokim** [comment]
It'll be fixed with upcoming version.

**Comment by shakvaal** [comment]
Still doesn't start on Windows 7 x64. <:-(
HarooPad v0.12.2.

**Comment by roose** [comment]
After launch I have 2 processes and no one windows.
Windows 8.1 x64,  HarooPad v0.12.2.
in log file:

| Information | Description |
| --- | --- |
| Type | Error |
| Date | Fri Nov 21 2014 07:20:52 GMT+0600 |
| File | file:///C:/Users/.../Temp/nw2812_7994/index.html |
| Line Number | 1 |
| Message | Uncaught SyntaxError: Unexpected token ﻿ |

**Comment by rhiokim** [comment]
Haroopad do not working perfect on window x64 system not yet. and I don't know why occur this issue. The next version is planned to support x64 systems.  Please wait few days.

**Comment by shakvaal** [comment]
@rhiokim Yay! Nice news)

**Comment by blfunex** [comment]
i have the same problem but here is what i think is the problem: the javascript snapshot is maybe made   with a different version of nwc that the nw.exe which haroo is made of.

**Comment by Blackgen** [comment]
Same Problem for me!
Was working well the first time and now it doesn't start anymore. (Win 8.1 64 bit)
On my other pc its working just fine (Win 10 64 bit)

Edit: 32 bit version isn't working as well..

**Comment by Ataginsky** [comment]
Hi,

For me, does not start at all.
Cannot repaire, tried 32 and 64 bit versions..

Version: 0.13.1
