### ISSUE TITLE
inline math shows as display, eats rest of paragragh

### ISSUE THREAD

**Issue by cben** [rhiokim/haroopad#463]
Display math works nicely but inline is misbehaving. haroopad-v0.13.0-x64.deb on lubuntu 14.10.
Same problem both in editor preview and Export -> HTML file.

On example from http://pad.haroopress.com/page.html?f=sample-mathematics:

https://gist.github.com/cben/24e48d7c876f6fb2c064
rendered HTML: https://rawgit.com/cben/24e48d7c876f6fb2c064/raw/3f4130dbba11fd21394859a2575c797799f5cb07/index.html
- `$$$\sqrt{3x-1}+(1+x)^2$$$` at the end is rendered as display math. (Same when I tried single dollars with corresponding Preferences option.)
- the text that follows it in the paragragh disappeared (not in the HTML at all).

**Comment by rhiokim** [comment]
It'll be fixed with upcoming version.

**Comment by wiwie** [comment]
still buggy for me in version v0.13.1 on ubuntu x64.

**Comment by sp4ghet** [comment]
Same, still getting this issue on the latest Windows x64 v0.13.1
